# Generated by Django 3.1.7 on 2021-02-27 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('email', models.EmailField(max_length=254)),
                ('category', models.CharField(choices=[('Question', 'question'), ('Other', 'other')], default='question', max_length=10)),
                ('subject', models.CharField(max_length=90)),
                ('body', models.TextField()),
            ],
        ),
    ]
